fix: Build issue on Mac ARM
Since the project is actually only used on Linux,
npm didn't have installed packaged needed for
Mac ARM.

I just needed to force install rspack to get the
needed packages. I took the opportunity to upgrade
rspack version.

It fixes:

```
npm run start

> front@0.1.0 start
> PORT=5000 rsbuild dev

node:internal/modules/cjs/loader:1410
  const err = new Error(message);
              ^

Error: Cannot find module '@rspack/binding-darwin-arm64'
```